### ISSUE TITLE
Use WIFI TX/RX instead of ESP?

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/easy-connect#10]
Should we use WIFI TX/RX instead? 

```
#ifdef MBED_CONF_APP_ESP8266_DEBUG
ESP8266Interface wifi(MBED_CONF_APP_WIFI_TX, MBED_CONF_APP_WIFI_RX, MBED_CONF_APP_ESP8266_DEBUG);
#else
ESP8266Interface wifi(MBED_CONF_APP_WIFI_TX, MBED_CONF_APP_WIFI_RX);
#endif
```

**Comment by JanneKiiskila** [comment]
Then have board specific changes for those, like in mbed-os-example-client

        "NUCLEO_F401RE": {
            "wifi-tx": "PA_11",
            "wifi-rx": "PA_12"
        },
        "NUCLEO_F411RE": {
            "wifi-tx": "PA_11",
            "wifi-rx": "PA_12"

**Comment by janjongboom** [comment]
As said in the PR, copying here for clarity:

I don't agree to rename these to `WIFI_TX`. Currently they're already called `ESP8266_TX` plus they are already overridable. I don't want to call it `WIFI_TX` because it's only related to WiFi modules that work over UART (ergo the ESP8266). If we're going to see WiFI modules over other protocols (or built-in to the platform like Realtek) it does not make sense to have this setting.

Also: compatibility with libraries using easy-connect right now. There are a number of workshops and examples that mention MBED_CONF_APP_ESP8266_TX and I don't want them to break (I did something to maintain compatibility of the change to MBED_CONF_APP_WIFI_SSID in easy-connect.h already).
