### ISSUE TITLE
Question: Why is everything defined in easy-connect.h?

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/easy-connect#49]
I was looking into easy-connect sometime ago when reviewing its integration with one of our sample applications (tls-client). At some point I ran into the compiler "multiple definition for..." problem, just like in [this](https://github.com/ARMmbed/easy-connect/issues/33) already closed ticket. After a brief look at the code in easy-connect.h it seems the problem is that all the functions/objects are defined in the header.

In practice, this is not a huge problem as one just has to be careful to include easy-connect.h and then include other headers such as TCPSocket or NetworkInterface wherever needed. However, I just wanted to ask why is everything in the header instead of splitting it into .h and .c (or .cpp) files?

**Comment by janjongboom** [comment]
Historically this was just a simple header file, maybe now is the time to split it up?

cc @JanneKiiskila

**Comment by JanneKiiskila** [comment]
Yes, I did do a PR already some time ago, but you @janjongboom did not like it at that point of time. Personally, I think code should always *only* be in `.c/.cpp` files, as otherwise you run into issues like this and secondly also easily dead-unnecessary code in the app as well, if you do not use something like `.mbedignore`.

**Comment by janjongboom** [comment]
By now I'd be open to split it up.

**Comment by JanneKiiskila** [comment]
And we have now PR to resolve that #59.

**Comment by JanneKiiskila** [comment]
#59 merged in, closing.
